added a lot more options
Makefile:
    changed default CFLAGS to use -std=gnu11

configure.ac:
    addition of AC_CHECK_HEADER([assert.h])

btcapi.h:
    small stylistic changes

cmdlineutils.h:
    defined macro 'noreturn' to C11's _Noreturn
    changed exit functions (help, version) to _Noreturn functions
    set all arguments arguments to const char *const

cmdlineutils.c:
    added new options to help() - -b, -p, -s

main.c:
    inclusion of assert.h
    addition of -b, -p, -s arguments
    various optimisations

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3492,6 +3492,14 @@ fi
 done
 
 
+ac_fn_c_check_header_mongrel "$LINENO" "assert.h" "ac_cv_header_assert_h" "$ac_includes_default"
+if test "x$ac_cv_header_assert_h" = xyes; then :
+
+else
+  echo "  ./configure: error: assert.h not found"; exit 1
+fi
+
+
 ac_fn_c_check_header_mongrel "$LINENO" "stdlib.h" "ac_cv_header_stdlib_h" "$ac_includes_default"
 if test "x$ac_cv_header_stdlib_h" = xyes; then :
 
